# Generated by Django 4.1.7 on 2024-02-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_creado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='creado_em',
            new_name='creado_en',
        ),
    ]
